[tool.black]
target-version = ["py37", "py38"]
line-length = 80

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_tests = "tests"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,TESTS,LOCALFOLDER"

[tool.poetry]
name = "Mopidy-YTMusic"
version = "0.4.0"
description = "Mopidy extension for playing music/managing playlists in YouTube Music"
authors = ["Ozymandias (Tomas Ravinskas) <tomas.rav@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Mopidy = ">=3.4,<5"
ytmusicapi = ">=1.9,<2"
yt-dlp = ">=2024.1.1"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0"
flake8 = "^5.0"
isort = "^5"
black = { version = "*", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."mopidy.ext"]
ytmusic = "mopidy_ytmusic:Extension"
